foreground   #ecd9d2
background   #211921
cursor       #ecd9d2

color0       #211921
color8       #a59793
color1       #AF9096
color9       #AF9096
color2       #A4919A
color10      #A4919A
color3       #D69998
color11      #D69998
color4       #CD9BA2
color12      #CD9BA2
color5       #EDB2A9
color13      #EDB2A9
color6       #BFC1B3
color14      #BFC1B3
color7       #ecd9d2
color15      #ecd9d2
