# Shell variables
# Generated by 'wal'
wallpaper='/home/ayush/wallpapers/76.jpg'

# Special
background='#211921'
foreground='#ecd9d2'
cursor='#ecd9d2'

# Colors
color0='#211921'
color1='#AF9096'
color2='#A4919A'
color3='#D69998'
color4='#CD9BA2'
color5='#EDB2A9'
color6='#BFC1B3'
color7='#ecd9d2'
color8='#a59793'
color9='#AF9096'
color10='#A4919A'
color11='#D69998'
color12='#CD9BA2'
color13='#EDB2A9'
color14='#BFC1B3'
color15='#ecd9d2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
