--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayush/wallpapers/76.jpg"

-- Special
background="#211921"
foreground="#ecd9d2"
cursor="#ecd9d2"

-- Colors
color0="#211921"
color1="#AF9096"
color2="#A4919A"
color3="#D69998"
color4="#CD9BA2"
color5="#EDB2A9"
color6="#BFC1B3"
color7="#ecd9d2"
color8="#a59793"
color9="#AF9096"
color10="#A4919A"
color11="#D69998"
color12="#CD9BA2"
color13="#EDB2A9"
color14="#BFC1B3"
color15="#ecd9d2"
